version: 1
apps:
  backend:
    deploy_path: /home/sisadmin/public_html/v1.sis-administration.com
    health_check_url: https://v1.sis-administration.com/up
    database: mysql

  frontend:
    deploy_path: /home/sisadmin/sis-web
    health_check_url: https://sis-administration.com
    build_env:
      NEXT_PUBLIC_API_URL: https://v1.sis-administration.com/api/v1
